// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxIpQrV9Fk8kunJNQkTa-F-SDMl4xbMU',
    appId: '1:478185234712:android:89d339be84815fbafffe6d',
    messagingSenderId: '478185234712',
    projectId: 'messengerapp-adea0',
    storageBucket: 'messengerapp-adea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1fX-VHAupcsO7dOdAdxrQkmxSe_jvoJQ',
    appId: '1:478185234712:ios:c413a8bebc0ab080fffe6d',
    messagingSenderId: '478185234712',
    projectId: 'messengerapp-adea0',
    storageBucket: 'messengerapp-adea0.appspot.com',
    iosBundleId: 'com.example.testtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvKsFX7bWIj19tXH8OammR3XTB_ODNWTM',
    appId: '1:478185234712:web:b5393dabb05086ebfffe6d',
    messagingSenderId: '478185234712',
    projectId: 'messengerapp-adea0',
    authDomain: 'messengerapp-adea0.firebaseapp.com',
    storageBucket: 'messengerapp-adea0.appspot.com',
  );
}
